# Generated by Django 5.1.2 on 2024-10-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='If user does not have access to course, can they see this?'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('soon', 'Coming soon'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
